wandb_version: 1

learning_rate:
  desc: null
  value: 0.0003
architecture:
  desc: null
  value: LeNET
dataset:
  desc: null
  value: BPS Microscopy Mouse Dataset
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685744510.728974
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.10
      5: 0.15.3
      8:
      - 5
